-- Backfill consolidated document_entities from legacy typed tables.
-- Run after document_entities_single_table.sql and before dropping typed tables.

insert into public.document_entities (
  document_id,
  drid,
  mrid,
  full_text,
  document_type,
  classification_confidence,
  organization_name,
  recipient_name,
  sender_name,
  contact_person_name,
  recipient_uen,
  reference_number,
  claimant_name,
  claimant_email,
  respondent_name,
  respondent_email,
  document_date,
  deadline_date,
  action_required,
  account_name,
  page_start,
  page_end,
  page_count,
  pdf_path,
  original_pdf_path,
  priority,
  status
)
select
  d.id as document_id,
  coalesce(u.drid, d.drid, '') as drid,
  coalesce(u.mrid, mi.mrid, '') as mrid,
  u.full_text,
  coalesce(u.document_type, d.classification_label, 'UNKNOWN') as document_type,
  coalesce(u.classification_confidence, d.classification_confidence) as classification_confidence,
  u.organization_name,
  u.recipient_name,
  u.sender_name,
  u.contact_person_name,
  u.recipient_uen,
  u.reference_number,
  l.claimant_name,
  l.claimant_email,
  l.respondent_name,
  l.respondent_email,
  u.document_date,
  u.deadline_date,
  coalesce(u.action_required, false) as action_required,
  i.account_name,
  u.page_start,
  u.page_end,
  u.page_count,
  u.pdf_path,
  u.original_pdf_path,
  coalesce(u.priority, 'MEDIUM') as priority,
  coalesce(u.status, 'D2_CLASSIFIED') as status
from public.documents d
left join public.mail_items mi on mi.id = d.mail_item_id
left join public.universal_info u on u.document_id = d.id
left join public.legal_entities l on l.document_id = d.id
left join public.invoice_entities i on i.document_id = d.id
on conflict (document_id) do update
set
  drid = excluded.drid,
  mrid = excluded.mrid,
  full_text = excluded.full_text,
  document_type = excluded.document_type,
  classification_confidence = excluded.classification_confidence,
  organization_name = excluded.organization_name,
  recipient_name = excluded.recipient_name,
  sender_name = excluded.sender_name,
  contact_person_name = excluded.contact_person_name,
  recipient_uen = excluded.recipient_uen,
  reference_number = excluded.reference_number,
  claimant_name = excluded.claimant_name,
  claimant_email = excluded.claimant_email,
  respondent_name = excluded.respondent_name,
  respondent_email = excluded.respondent_email,
  document_date = excluded.document_date,
  deadline_date = excluded.deadline_date,
  action_required = excluded.action_required,
  account_name = excluded.account_name,
  page_start = excluded.page_start,
  page_end = excluded.page_end,
  page_count = excluded.page_count,
  pdf_path = excluded.pdf_path,
  original_pdf_path = excluded.original_pdf_path,
  priority = excluded.priority,
  status = excluded.status,
  updated_at = now();
